# Generated by Django 5.2.7 on 2025-11-22 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#446A7D', max_length=7),
        ),
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.IntegerField(default=5, help_text='Время чтения в минутах'),
        ),
        migrations.AddField(
            model_name='post',
            name='theory_content',
            field=models.TextField(default='Теоретический материал будет добавлен позже.', help_text='Теоретическая часть'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('solution', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='blog.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
