# Generated by Django 5.2.7 on 2025-11-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_color_post_difficulty_post_reading_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='theory_content',
            field=models.TextField(blank=True, help_text='Теоретическая часть', null=True),
        ),
    ]
