# Generated by Django 5.2.7 on 2025-11-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_theory_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Текстовый ответ'), ('number', 'Числовой ответ'), ('formula', 'Математическая формула'), ('multiple', 'Множественный выбор')], default='text', help_text='Тип ответа для правильной проверки', max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Правильный ответ для автоматической проверки', max_length=200),
        ),
        migrations.AddField(
            model_name='problem',
            name='multiple_choices',
            field=models.TextField(blank=True, help_text='Варианты ответов через запятую (для множественного выбора)'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tolerance',
            field=models.FloatField(default=0.01, help_text='Допустимая погрешность для числовых ответов'),
        ),
    ]
